FakeNewsProject/FakeNewsProject/Models/Story.cs
namespace FakeNewsProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Story")]
    public partial class Story
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Story()
        {
            Favorites = new HashSet<Favorite>();
            StoryTags = new HashSet<StoryTag>();
        }

        public int ID { get; set; }

        public int UserID { get; set; }

        [Required]
        [StringLength(200)]
        public string Title { get; set; }

        [Column(TypeName = "text")]
        [Required]
        public string Body { get; set; }

        [Column(TypeName = "text")]
        public string Summary { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Date"), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime PostDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }

        public virtual User User { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoryTag> StoryTags { get; set; }
    }
}

FakeNewsProject/FakeNewsProject/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FakeNewsProject.Models;
using FakeNewsProject.ViewModels;

namespace FakeNewsProject.Controllers
{
    public class StoriesController : Controller
    {
        private FakeNewsContext db = new FakeNewsContext();

        // GET: Stories
        public ActionResult Index()
        {
            var stories = db.Stories.Include(s => s.User);
            return View(stories.ToList());
        }

        // GET: Stories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Story story = db.Stories.Find(id);
            if (story == null)
            {
                return HttpNotFound();
            }
            return View(story);
        }

        /// <summary>
        /// HttpGet method
        /// Shows story creation page. Will need to set a way to get user's ID
        /// from log in. Story model requires the user's ID.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            Story postSetup = db.Stories.Create();
            postSetup.UserID = 1;
            postSetup.PostDate = DateTime.Now;

            var tags = db.Tags.OrderBy(t => t.Name).ToList();

            // create a list of viewmodels to associate a boolean with each tag
            var tagOptions = new List<TagSelect>();
            foreach (Tag t in tags)
            {
                tagOptions.Add(new TagSelect { TagName = t.Name, TagID = t.ID});
            }

            TagStories ts = new TagStories { TheStory = postSetup, TheTags = tagOptions };
            return View(ts);
        }

        [HttpPost]
        public ActionResult Create(TagStories newPost)
        {
            if (ModelState.IsValid)
            {
                db.Stories.Add(newPost.TheStory);
                // create a link between story and tag for all selected tags
                foreach(var tag in newPost.TheTags)
                {
                    if (tag.IsSelected)
                    {
                        // not how to do this, but don't care at this point
                        db.StoryTags.Add(new StoryTag { StoryID = db.Stories.Count() + 1, TagID = tag.TagID });
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newPost);
        }

        // GET: Stories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Story story = db.Stories.Find(id);
            if (story == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "ID", "FName", story.UserID);
            return View(story);
        }

        // POST: Stories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserID,Title,Body,Summary,PostDate")] Story story)
        {
            if (ModelState.IsValid)
            {
                db.Entry(story).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Users, "ID", "FName", story.UserID);
            return View(story);
        }

        // GET: Stories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Story story = db.Stories.Find(id);
            if (story == null)
            {
                return HttpNotFound();
            }
            return View(story);
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Story story = db.Stories.Find(id);
            db.Stories.Remove(story);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        public ActionResult Save(int? id, int? storyId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (db.Users.Find(id) == null)
            {
                return RedirectToAction("Details");
            }
            Favorite fav = new Favorite();
            fav.UserID = (int)id;
            fav.StoryID = (int)storyId;
            db.Favorites.Add(fav);
            db.SaveChanges();
            return RedirectToAction("Details","Users", id);

        }
    }
}

FakeNewsProject/FakeNewsProject/Views/Stories/Create.cshtml
@model FakeNewsProject.ViewModels.TagStories

@{
    ViewBag.Title = "Create";
}

<center><h2>Create a new Fake News story.</h2></center>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @* User ID will be hard coded until we set up a way for them to log into before reaching
            this page. **NEEDS FIX** *@

        @Html.HiddenFor(model => model.TheStory.UserID)

        @*PostDate is generated by the controller. User should not be able
            to modify it unless we want them to have the ability to create
            fake dates as well. Probably would need a check then to keep
            in the proper range for the database. *@
        @Html.HiddenFor(model => model.TheStory.PostDate)



        <div class="form-group">
            @Html.LabelFor(model => model.TheStory.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TheStory.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TheStory.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TheStory.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TheStory.Body, 5, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TheStory.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TheStory.Summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TheStory.Summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TheStory.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Select Tags", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @for (int i = 0; i < Model.TheTags.Count; i++)
                {
                    @Html.CheckBoxFor(x => x.TheTags[i].IsSelected, new { @class = "checkbox-inline"})
                    @Html.LabelFor(x => x.TheTags[i].IsSelected, Model.TheTags[i].TagName)
                    @Html.HiddenFor(x => x.TheTags[i].TagName)
                    @Html.HiddenFor(x => x.TheTags[i].TagID)
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FakeNewsProject/FakeNewsProject/Views/Stories/Delete.cshtml
@model FakeNewsProject.Models.Story

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Story</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Summary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FakeNewsProject/FakeNewsProject/Views/Stories/Details.cshtml
@model FakeNewsProject.Models.Story

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <h2>@Html.DisplayFor(model => model.Title)</h2>
    <div>
        <hr />
        <dl class="dl-horizontal" style="font-size:18px">
            <dt>
                @Html.DisplayNameFor(model => model.User.UserName)
            </dt>

            <dd>
                @Html.ActionLink(Model.User.UserName, "Details", "Users", new { ID = Model.User.ID }, null)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PostDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PostDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Body)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Body)
            </dd>
        </dl>
        <hr />
        <!--This area takes user input in the form of text (for now). The input should be
            the user ID. That will make a 'favorite' of this story for future use. SJA-->
        <div style="text-align:right" >
            <h4>
                Want to save this article for later? Just input your user ID and click<br />
                submit!The article will be saved in your user profile!
            </h4>
            @using (@Html.BeginForm("Save", "Stories", new { id = Model.User.ID, storyId = Model.ID }))
            {
                <input type="text" name="userID" />
                <input type="submit" value="Submit">
            }
        </div>
    </div>
</body>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

FakeNewsProject/FakeNewsProject/Views/Stories/Edit.cshtml
@model FakeNewsProject.Models.Story

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Story</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FakeNewsProject/FakeNewsProject/Views/Stories/Index.cshtml
@model IEnumerable<FakeNewsProject.Models.Story>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Summary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.User.UserName, "Details", "Users", new { ID = item.User.ID }, null)
        </td>
        <td>
            @Html.ActionLink(item.Title, "Details", new { ID = item.ID })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Summary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostDate)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ID })

        </td>
    </tr>
}

</table>