IPGMMS/IPGMMS/Controllers/PortalController.cs
using IPGMMS.Abstract;
using IPGMMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using System.Diagnostics;
using IPGMMS.ViewModels;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;

namespace IPGMMS.Controllers
{
    [AdminAuthorize(Roles = "Admin")]
    public class PortalController : MController
    {
        private IMemberRepository memberRepo;
        private IContactRepository contactRepo;

        public PortalController(IMemberRepository mRepo, IContactRepository cRepo)
        {
            memberRepo = mRepo;
            contactRepo = cRepo;
        }

        //***********************************************ADMIN PORTAL INDEX*****************************
        // GET: Portal
        public ActionResult Index()
        {
            //Set values to pass to the ViewBag
            var user = User.Identity;
            ViewBag.Name = user.Name;

            //Create items to add to the MemberReports ViewModel to pass to the view
            MemberReports reports = new MemberReports();
            reports.MemberCount = memberRepo.GetAllMembers.Count();
            reports.ActiveMemberCount = memberRepo.GetActiveMemberCount();
            reports.NewMemberLast30Count = memberRepo.GetNewMemberCount();
            reports.ExpiredMembersCount = memberRepo.ExpiredMembers.Count();
            reports.ExpiringMembersCount = memberRepo.ExpiringMembers.Count();
            reports.NewMembersCount = memberRepo.NewMembers.Count();
            reports.ExpiringMembers = memberRepo.ExpiringMembers.Take(3);
            reports.NewMembers = memberRepo.NewMembers.Take(3);
            reports.ExpiredMembers = memberRepo.ExpiredMembers.Take(3);
            
            return View(reports);
        }

        //***********************************************LIST MEMBER INFO*****************************
        
        public ActionResult ListMembers()
        {
            var members = memberRepo.GetAllMembers;
            return View(members.ToList());

        }
        

        //***********************************************DETAILED MEMBER INFO*****************************
        public ActionResult DetailMember()
        {
            return View("DetailMember");
        }

        //***********************************************ADD MEMBER***************************************
        // GET: Addmember()
        public ActionResult AddMember()
        {
            MemberCreate createMember = new MemberCreate();
            createMember.Levels = memberRepo.GetLevels;
            return View("AddMember", createMember);
        }

        // POST: AddMember()
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMember(MemberCreate infos)
        {

            if (ModelState.IsValid)
            {
                Member memb = infos.MemberInfo;
                ContactInfo mail = (ContactInfo)infos.MailingInfo;
                memb.Membership_Number = memberRepo.setMemberNumber(memb, mail);
                memb = memberRepo.InsertorUpdate(memb);
                // Mailing info is required.
                mail = contactRepo.InsertorUpdate(mail);
                contactRepo.LinkMailingContact(memb, mail);

                // Listing info is optional.
                ContactInfo list = infos.ListingInfo;
                list = contactRepo.InsertorUpdate(list);
                contactRepo.LinkListingContact(memb, list);

                Debug.WriteLine("Says it's valid but not really, maybe");
                return RedirectToAction("UpdateMember", new { id = memb.ID });
                //return View("DetailMember", memb);
            }

            infos.Levels = memberRepo.GetLevels;
            return View("AddMember", infos);
        }

        public ActionResult UpdateMember(int? id)
        {
            if (id == null)
            {
                id = 4;
            }
            MemberInfoViewModel info = new MemberInfoViewModel();
            info.MemberInfo = memberRepo.Find(id);
            //Try to get the Listing info from the contact repo. If there's no listing 
            //for this member, then the info.ListingInfo is set to null for this
            //ViewModel that is passed back to the view.
            try
            {
                info.ListingInfo = contactRepo.ListingInfoFromMID(id);
            }
            catch (System.InvalidOperationException)
            {
                info.ListingInfo = null;
            }
            //Try to get the Mailing info from the contact repo. If there's no listing 
            //for this member, then the info.MailingInfo is set to null for this
            //ViewModel that is passed back to the view.
            try
            {
                info.MailingInfo = contactRepo.MailingInfoFromMID(id);
            }
            catch (System.InvalidOperationException)
            {
                info.MailingInfo = null;
            }

            return View(info);
        }

        //***********************************************UPDATE MEMBER INFO*****************************
        /// <summary>
        /// This method is the GET for UpdateMemberInfo(). This takes in the memberID 
        /// (not to be confused with the memberNumber) and, if a valid memberID, returns
        /// a form that allows the user to update member information.
        /// </summary>
        /// <param name="memID"></param>
        /// <returns>The UpdateMemberInfo view. </returns>
        public ActionResult UpdateMemberInfo(int? memID)
        {
            if (memID == null)
            {
                return View(Request.UrlReferrer.ToString());
            }
            if (memberRepo.Find(memID) == null)
            {
                return View(Request.UrlReferrer.ToString());
            }

            MemberInfoVM memberinfo = new MemberInfoVM();
            memberinfo.Levels = memberRepo.GetLevels;
            memberinfo.MemberInfo = memberRepo.Find(memID);

            return View(memberinfo);
        }

        /// <summary>
        /// This method is the POST for UpdateMemberInfo(). This takes in a ViewModel parameter
        /// that holds a member object and a select list of membership levels. This method will
        /// save updates to the database and return the user to the UpdateMember page to view 
        /// their changes.
        /// </summary>
        /// <param name="memb"></param>
        /// <returns>If the model state is valid, this returns the user back to the UpdateMember view
        /// if it is not valid, it returns the user to the UpdateMemberInfo view with the ViewModel given.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMemberInfo(MemberInfoVM memb)
        {
            if (ModelState.IsValid)
            {
                var member = memb.MemberInfo;
                memberRepo.InsertorUpdate(member);
                MemberInfoViewModel memberDetails = new MemberInfoViewModel();
                memberDetails.MemberInfo = member;
                memberDetails.ListingInfo = contactRepo.ListingInfoFromMID(member.ID);
                memberDetails.MailingInfo = contactRepo.MailingInfoFromMID(member.ID);
                memb.Levels = memberRepo.GetLevels;
                return View("UpdateMember", memberDetails);
            }

            memb.Levels = memberRepo.GetLevels;
            return View(memb);
        }

        // GET: UpdateMemberMailing()
        public ActionResult UpdateMemberMailing(int? memID)
        {

            if (memID == null)
            {
                return View("Index");
                //return View(Request.UrlReferrer.ToString());
            }


            return View(contactRepo.MailingInfoFromMID(memID));
        }

        // POST: UpdateMemberMailing()
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMemberMailing(ContactInfo info)
        {
            if (ModelState.IsValid)
            {
                contactRepo.InsertorUpdate(info);
                MemberInfoViewModel memberDetails = new MemberInfoViewModel();
                var memID = contactRepo.getMemberID(info);
                memberDetails.MemberInfo = memberRepo.Find(memID);
                memberDetails.ListingInfo = contactRepo.ListingInfoFromMID(memID);
                memberDetails.MailingInfo = info;
                return View("UpdateMember", memberDetails);
            }
            return View(info);
        }

        // GET: UpdateMemberListing()
        public ActionResult UpdateMemberListing(int? memID)
        {
            if (memID == null)
            {
                return View("Index");
                //return View(Request.UrlReferrer.ToString());
            }

            return View(contactRepo.ListingInfoFromMID(memID));
        }

        // POST: UpdateMemberListing()
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMemberListing(ContactInfo info)
        {
            if (ModelState.IsValid)
            {
                contactRepo.InsertorUpdate(info);
                MemberInfoViewModel memberDetails = new MemberInfoViewModel();
                var memID = contactRepo.getMemberID(info);
                memberDetails.MemberInfo = memberRepo.Find(memID);
                memberDetails.ListingInfo = info;
                memberDetails.MailingInfo = contactRepo.MailingInfoFromMID(memID);
                return View("UpdateMember", memberDetails);
            }
            return View(info);
        }

        // Test & Certification section to be added to later when time permits.
        public ActionResult ListTests()
        {
            return RedirectToAction("UnderConstruction", "Home");
        }

        public ActionResult AddTest()
        {
            return RedirectToAction("UnderConstruction", "Home");
        }

IPGMMS/IPGMMS/Views/Portal/AJAXListMembers.cshtml
@model PagedList.IPagedList<IPGMMS.Models.Member>
@using PagedList.Mvc

@{
    ViewBag.Title = "List Members";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using (Ajax.BeginForm("ListMembers", "Portal", FormMethod.Post,
                                    new AjaxOptions
                                    {
                                        HttpMethod = "POST",
                                        InsertionMode = InsertionMode.Replace,
                                        UpdateTargetId = "CenterPartialUpdateFrame"
                                    }))
{
<p>
    Find by name: @Html.TextBox("SearchString")
    <input type="submit" value="Search" />
</p>
}

<table class="table">
    <tr>
        <th>
            @{ var memlvl = @Html.DisplayNameFor(model => model.FirstOrDefault().MemberLevel1.MLevel).ToString();}
            @Ajax.ActionLink(
            memlvl,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.mem_lvl },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var userName = @Html.DisplayNameFor(model => model.FirstOrDefault().UserName).ToString();}
            @Html.ActionLink(userName,"ListMembers","Portal", new { sortOrder = ViewBag.userName}, null)
            @*@Ajax.ActionLink(
            userName,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.userName },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })*@

        </th>
        <th>
            @{ var mem_num = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_Number).ToString();}
            @Ajax.ActionLink(
            mem_num,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.mem_num },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var date_start = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_SignupDate).ToString();}
            @Ajax.ActionLink(
            date_start,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.date_start },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var date_end = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_ExpirationDate).ToString();}
            @Ajax.ActionLink(
            date_end,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.date_end },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var f_name = @Html.DisplayNameFor(model => model.FirstOrDefault().FirstName).ToString();}
            @Ajax.ActionLink(
            f_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.f_name },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var m_name = @Html.DisplayNameFor(model => model.FirstOrDefault().MiddleName).ToString();}
            @Ajax.ActionLink(
            m_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.m_name },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var l_name = @Html.DisplayNameFor(model => model.FirstOrDefault().LastName).ToString();}
            @Ajax.ActionLink(
            l_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.lName },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var b_name = @Html.DisplayNameFor(model => model.FirstOrDefault().BusinessName).ToString();}
            @Ajax.ActionLink(
            b_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.b_name },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var website = @Html.DisplayNameFor(model => model.FirstOrDefault().Website).ToString();}
            @Ajax.ActionLink(
            website,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.website },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MemberLevel1.MLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_SignupDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_ExpirationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusinessName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Website)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>
<div>
    Page @(Model.PageNumber < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("ListMembers", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.currentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
        new AjaxOptions() { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "CenterPartialUpdateFrame" }))
</div>

IPGMMS/IPGMMS/Views/Portal/Index.cshtml
@model IPGMMS.ViewModels.MemberReports
@{
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
    ViewBag.Title = "Index";
}

<!--Admin dashboard Welcome Section--------------------------------------------------------->
<div class="w3-row">
    <div class="w3-twothird">
        <h2><i class="fa fa-dashboard"></i> Admin Dashboard - Welcome, @User.Identity.Name!</h2>
    </div>
    <div class="w3-third w3-right-align">
    </div>
</div>
<hr />
<!--Admin dashboard Section 1 * Info Boxes-------------------------------------------------->
<div class="w3-row-padding w3-margin-bottom">
    <div class="w3-third">
        <a class="removeTextDecor" href="@Url.Action("ListMembers", "Portal")">
            <div class="w3-container w3-padding-16 w3-card-4" id="adminDashInfo1">
                <div class="w3-left"><i class="fa fa-users w3-xxlarge"></i></div>
                <div class="w3-right"><h2>@Html.DisplayFor(model => model.MemberCount)</h2></div>
                <div class="w3-clear"></div>
                <h2 class="removeTextDecor">Total Members</h2>
            </div>
        </a>
    </div>
    <div class="w3-third">
        <div class="w3-container w3-padding-16 w3-card-4" id="adminDashInfo2">
            <div class="w3-left"><i class="fa fa-users w3-xxlarge"></i></div>
            <div class="w3-right"><h2>@Html.DisplayFor(model => model.ActiveMemberCount)</h2></div>
            <div class="w3-clear"></div>
            <h2>Active Members</h2>
        </div>
    </div>
    <div class="w3-third">
        <div class="w3-container w3-padding-16 w3-card-4" id="adminDashInfo3">
            <div class="w3-left"><i class="fa fa-user-plus w3-xxlarge"></i></div>
            <div class="w3-right"><h2>@Html.DisplayFor(model => model.NewMemberLast30Count)</h2></div>
            <div class="w3-clear"></div>
            <h2>New Members this Month</h2>
        </div>
    </div>
</div>
<hr />
<!--Admin dashboard Section 2 * Reports-------------------------------------------------------------------->
<div class="w3-row-padding w3-margin-bottom">

    <h2>Current Alerts</h2>
    <p>Showing top 3 results for each alert. To view the report in its entirety, click on the report header.</p>

    <div class="w3-half allowScroll">
        <a href="@Url.Action("ReportExpiringMember", "Portal")">
            <div class="w3-container w3-padding-16 w3-card-2 w3-hoverable" id="alertArea3">
                <div class="w3-left"><h3>Expiring Soon</h3></div>
                <div class="w3-right"><h2>@Html.DisplayFor(model => model.ExpiringMembersCount)</h2></div>
            </div>
        </a>
        <table class="w3-table w3-bordered w3-responsive w3-card-4 w3-small w3-hoverable">
            <tbody>
                @foreach (var item in Model.ExpiringMembers)
                {
                    <tr class="w3-hover-pale-yellow" onclick="location.href='@(Url.Action("UpdateMember/" + item.ID, "Portal"))'">
                        <td>
                            @Html.DisplayFor(modelItem => item.Membership_Number)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Membership_ExpirationDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MemberLevel1.MLevel)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="w3-half allowScroll">
        <a href="@Url.Action("ReportNewMember", "Portal")">
            <div class="w3-container w3-padding-16 w3-card-2 w3-hoverable" id="alertArea2">
                <div class="w3-left"><h3>New Members</h3></div>
                <div class="w3-right"><h2>@Html.DisplayFor(model => model.NewMembersCount)</h2></div>
            </div>
        </a>
        <table class="w3-table w3-bordered w3-card-4 w3-responsive w3-small w3-hoverable">
            <tbody>
                @foreach (var item in Model.NewMembers)
            {
                    <tr class="w3-hover-pale-green" onclick="location.href='@(Url.Action("UpdateMember/" + item.ID, "Portal"))'">
                        <td>
                            @Html.DisplayFor(modelItem => item.Membership_Number)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Membership_ExpirationDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MemberLevel1.MLevel)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>
<div class="w3-row-padding w3-margin-bottom">
    <div class="w3-half allowScroll">
        <a href="@Url.Action("ReportExpiredMembers", "Portal")">
            <div class="w3-container w3-padding-16 w3-card-2" id="alertArea1">
                <div class="w3-left">
                    <h3>Expired Members</h3>
                </div>
                <div class="w3-right"><h2>@Html.DisplayFor(model => model.ExpiredMembersCount)</h2></div>
            </div>
        </a>
        <table class="w3-table w3-bordered w3-card-4 w3-responsive w3-small w3-hoverable">
            <tbody>
                @foreach (var item in Model.ExpiredMembers)
                {
                    <tr class="w3-hover-pale-red" onclick="location.href='@(Url.Action("UpdateMember/" + item.ID, "Portal"))'">
                        <td>
                            @Html.DisplayFor(modelitem => item.Membership_Number)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Membership_ExpirationDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MemberLevel1.MLevel)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<hr />
<!--Admin dashboard Section 3 * Social Media Center------------------------------------------------------->
<div class="w3-row-padding w3-margin-bottom">
    <h2>Social Media Center</h2>
    <div class="w3-half">
        <a href="#" class="removeTextDecor socialMediaIcons fa fa-facebook w3-xlarge w3-card-4"></a>
        <a href="#" class="removeTextDecor socialMediaIcons fa fa-twitter w3-xlarge w3-card-4"></a>
        <a href="#" class="removeTextDecor socialMediaIcons fa fa-google w3-xlarge w3-card-4"></a>
        <a href="#" class="removeTextDecor socialMediaIcons fa fa-linkedin w3-xlarge w3-card-4"></a>
        <a href="#" class="removeTextDecor socialMediaIcons fa fa-youtube w3-xlarge w3-card-4"></a>
        <a href="#" class="removeTextDecor socialMediaIcons fa fa-instagram w3-xlarge w3-card-4"></a>
    </div>
</div>

IPGMMS/IPGMMS/Views/Portal/ListMembers.cshtml
@model IEnumerable<IPGMMS.Models.Member>

@{
    ViewBag.Title = "List Members";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>


<h1>View/Update Members</h1>
<hr />
<table id="orderedTable" class="w3-table-all w3-card-4 w3-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_SignupDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_ExpirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().BusinessName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Website)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().MemberLevel1.MLevel)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr class="w3-hover-blue" onclick="location.href = '@(Url.Action("UpdateMember/" + item.ID, "Portal"))'">
                <td>
                    @Html.DisplayFor(modelItem => item.Membership_Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Membership_SignupDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Membership_ExpirationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MiddleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Website)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberLevel1.MLevel)
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
    @Scripts.Render("~/Scripts/data_tables.js")
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
}

IPGMMS/IPGMMS/Views/Portal/ReportLandingPage.cshtml
@{
    ViewBag.Title = "ReportLandingPage";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<h2>Reports</h2>
<br />
<div class="row">
    <div class="col-lg-8">
        <table class="w3-table-all  w3-responsive">
            <tr>
                <th>Report Name</th>
                <th>Report Description</th>
            </tr>
            <tr>
                <td id="memberListLinks"><a href="@Url.Action("ReportExpiredMembers", "Portal")">Expired Members</a></td>
                <td>This report lists all expired members.</td>
            </tr>
            <tr>
                <td id="memberListLinks"><a href="@Url.Action("ReportExpiringMember", "Portal")">Expiring Members</a></td>
                <td>This report lists all members expiring within two months.</td>
            </tr>
            <tr>
                <td id="memberListLinks"><a href="@Url.Action("ReportNewMember", "Portal")">New Members</a></td>
                <td>This report lists all members who have been added but still require a member level.</td>
            </tr>
        </table>
    </div>
</div>