IPGMMS/IPGMMS/Controllers/MapController.cs
using IPGMMS.Abstract;
using IPGMMS.Models;
using IPGMMS.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IPGMMS.Controllers
{
    public class MapController : MController
    {
        private IMemberRepository memberRepo;
        private IContactRepository contactRepo;
        private static HttpClient client = new HttpClient();
        private string apiUrl = "https://maps.googleapis.com/maps/api/geocode/json?address=";
        private string apiKey = "&key=AIzaSyCMzq0fLRdhVhgT42oiQrfu-gz9m0ftvhk";

        public MapController(IMemberRepository mRepo, IContactRepository cRepo)
        {
            memberRepo = mRepo;
            contactRepo = cRepo;
        }
        // GET: Map
        /// <summary>
        /// Shows map centered on the zip code given. If no zip code is given
        /// or the one entered is invalid, it will use 97304 as default. This
        /// is the zip code of the IPG HQ.
        /// </summary>
        /// <param name="zipCode">give as string to allow for chars</param>
        /// <returns>returns view and MapJson objects</returns>
        public async Task<ActionResult> Index(string zipCode)
        {
            // Tower of London zip code -> "EC3N 4AB";
            if (zipCode == null)
            {
                // Default Salem, OR
                zipCode = "97304";
            }
            // Get active members with Google readable addresses
            ViewBag.locations = await GetMapInfos();
            ViewBag.center = await GetCenter(zipCode);
            if (ViewBag.center == null)
            {
                ViewBag.center = await GetCenter("97304");
            }
            return View();
        }

        /// <summary>
        /// Retrieves all listing addresses from the database in order to find
        /// the longitude and latitude coordinates.
        /// </summary>
        /// <returns></returns>
        private async Task<List<MapInfo>> GetMapInfos()
        {
            List<MapInfo> mapinfos = new List<MapInfo>();

            var memberIDs = memberRepo.GetActiveMemberIDs();

            List<ContactInfo> listingInfo = new List<ContactInfo>();

            // Tuple memberID, listInfo
            List<Tuple<int, ContactInfo>> tempList = new List<Tuple<int, ContactInfo>>();

            for (int i = 0; i < memberIDs.Length; i++)
            {
                ContactInfo listInfo = contactRepo.ListingInfoFromMID(memberIDs[i]);
                if (listInfo.StateName != null)
                {
                    tempList.Add(new Tuple<int, ContactInfo>(memberIDs[i], listInfo));
                }
            }

            foreach (var tup in tempList)
            {

                var address = tup.Item2.StreetAddress + ",+"
                            + tup.Item2.City + ",+"
                            + tup.Item2.StateName;
                address = address.Replace(" ", "+");
                Debug.WriteLine(address);

                // Check to see if the address given will return a valid map
                // location.
                MapJson locationCheck = await GetLocation(address);
                if (locationCheck != null)
                {
                    MapInfo mapinfo = new MapInfo();
                    Member member = memberRepo.Find(tup.Item1);

                    mapinfo.Position = locationCheck.results.FirstOrDefault().geometry.location;
                    mapinfo.FullName = member.FullName;
                    mapinfo.BusinessName = member.BusinessName;
                    mapinfo.MemberLevel = member.MemberLevel1.MLevel;
                    mapinfo.Website = member.Website;
                    mapinfo.Address1 = tup.Item2.StreetAddress;
                    mapinfo.Address2 = tup.Item2.City + ", "
                                     + tup.Item2.StateName + " "
                                     + tup.Item2.PostalCode;
                    mapinfo.PhoneNumber = tup.Item2.PhoneNumber;
                    mapinfo.Email = tup.Item2.Email;
                    mapinfo.MemberID = member.ID;
                    
                    mapinfos.Add(mapinfo);
                }
            }
            return mapinfos;
        }


        /// <summary>
        /// Usings Google Geocoder API to retrieve the longitude and latitude
        /// coordinates (and other info) for a given address.
        /// </summary>
        /// <param name="address">streetnum+road+city+state</param>
        /// <returns>C# object representing the JSON from Google</returns>
        public async Task<MapJson> GetLocation(string address)
        {
            //Task<MapJson>
            // examplehttps://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=

            //address = "1600+Amphitheatre+Parkway,+Mountain+View,+CA";
            string repUrl = apiUrl + address + apiKey;
            HttpResponseMessage response = await client.GetAsync(repUrl).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
            {
                string apiResponse = await response.Content.ReadAsStringAsync();

                MapJson testObject = JsonConvert.DeserializeObject<MapJson>(apiResponse);

                // Will only add good addresses
                if (testObject.status == "OK")
                {
                    return testObject;
                }
            }

            return null;
        }

        /// <summary>
        /// Gets the center location to center the map at that locatoin
        /// </summary>
        /// <param name="address">A valid address formatted in an addressy manner</param>
        /// <returns>MapJson object to center the map</returns>
        private async Task<MapJson> GetCenter(string address)
        {

            string repUrl = apiUrl + ",&components=postal_code:" + address + apiKey;
            HttpResponseMessage response = await client.GetAsync(repUrl).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                MapJson center = JsonConvert.DeserializeObject<MapJson>(apiResponse);

                // Returns only good addresses.
                if (center.status == "OK")
                {
                    return center;
                }
            }
            return null;
        }
    }
}

IPGMMS/IPGMMS/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

IPGMMS/IPGMMS/Views/Shared/_AdminNav.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="navbar navbar-fixed-left">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">
            <img src="~/Content/Images/IPGLogo2.jpeg" alt="Top Logo" />
        </a>
    </div>
    <ul class="nav navbar-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Members</a>
            <ul class="dropdown-menu" role="menu">
                <li>
                    @Ajax.ActionLink(
                    "View",
                    "ListMembers",
                    "Portal",
                    new AjaxOptions
                    {
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "CenterPartialUpdateFrame"
                    })
                </li>
                <li>
                    @Ajax.ActionLink(
                   "Add",
                   "AddMember",
                   "Portal",
                   new AjaxOptions
                   {
                       HttpMethod = "GET",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "CenterPartialUpdateFrame"
                   })
                </li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tests</a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">View</a></li>
                <li><a href="#">Add</a></li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Certifications</a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">View</a></li>
                <li><a href="#">Add</a></li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Test Results</a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">View</a></li>
                <li><a href="#">Add</a></li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
    </ul>
</div>

IPGMMS/IPGMMS/Views/Shared/_AdminPortalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - IPG Admin Portal</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/ipgLogoFavicon.ico" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/w3.css")
    @Styles.Render("~/Content/AdminPortalSharedLayout.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="w3-white">

    <!--Top Nav Bar-->
    <div class="w3-navbar w3-black w3-hide-small">
        @Html.Partial("_LoginPartial")
    </div>
    <div>
        @Html.Partial("_AdminSideNav")
    </div>

    <!-- Navbar on small screens (Hidden on medium and large screens) --------------------------------->
    <div class="w3-bar w3-top w3-black w3-small">
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-left w3-hide-large w3-hide-medium" onclick="w3_open_bar()"><i class="fa fa-bars"></i></a>
    </div>
    <nav class="w3-sidebar w3-bar-block w3-black w3-card-2 w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="adminPortalBar">
        <a href="javascript:void(0)" onclick="w3_close_bar()" class="w3-bar-item w3-button w3-padding-16">× Close</a>
        <a href="@Url.Action("Index", "Portal")" onclick="w3_close_bar()" class="w3-bar-item w3-button">DASHBOARD</a>
        <a href="@Url.Action("ListMembers","Portal")" onclick="w3_close_bar()" class="w3-bar-item w3-button">MEMBERS</a>
        <a href="@Url.Action("ReportLandingPage", "Portal")" onclick="w3_close_bar()" class="w3-bar-item w3-button">REPORTS</a>
        <a href="#pricing" onclick="w3_close_bar()" class="w3-bar-item w3-button">RESULTS</a>
        <a href="#contact" onclick="w3_close_bar()" class="w3-bar-item w3-button">TEST CERT</a>
        <a href="@Url.Action("Index", "Home")" onclick="w3_close_bar()" class="w3-bar-item w3-button">IPG HOME</a>
        <a href="javascript:document.getElementById('logoutForm').submit()" onclick="w3_close_bar()" class="w3-bar-item w3-button">LOG OFF</a>
    </nav>

    <!-- END PAGE CONTENT -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/SharedLayout.js")
    @RenderSection("scripts", required: false)

    <!-- Page Content -->
    <div class="w3-padding-medium" id="main">
        <div>
            @RenderBody()
        </div>
    </div>

    <!-- Footer -->
    <footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge" id="mainFooter">
        <p class="w3-medium">Powered by StarTech</p>
        <!-- End footer -->
    </footer>
</body>

</html>

IPGMMS/IPGMMS/Views/Shared/_AdminSideNav.cshtml
<!-- Side Navigation for Admin Portal -->
<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center w3-black" style="position:fixed">
    <div class="dropdown">
        <a href="@Url.Action("Index", "Portal")" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
            <i class="fa fa-home w3-xxlarge"></i>
            <p>ADMIN HOME</p>
        </a>
    </div>
    <div class="dropdown">
        <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
            <i class="fa fa-user w3-xxlarge"></i>
            <p>MEMBERS</p>
        </a>
        <div class="dropdown-content">
            <a href="@Url.Action("AddMember", "Portal")">Add Member</a>
            <a href="@Url.Action("ListMembers","Portal")">View/Update Members</a>
        </div>
    </div>
    <div class="dropdown">
        <a href="@Url.Action("ReportLandingPage", "Portal")" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
            <i class="fa fa-file w3-xxlarge"></i>
            <p>REPORTS</p>
        </a>
    </div>
    <div class="dropdown">
        <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
            <i class="fa fa-clipboard w3-xxlarge"></i>
            <p>RESULTS</p>
        </a>
        <div class="dropdown-content">
            <a href="#">TO BE ADDED</a>
            <a href="#">TO BE ADDED</a>
        </div>
    </div>
    <div class="dropdown">
        <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
            <i class="fa fa-list-alt w3-xxlarge"></i>
            <p>TEST CERT</p>
        </a>
        <div class="dropdown-content">
            <a href="#">TO BE ADDED</a>
            <a href="#">TO BE ADDED</a>
        </div>
    </div>
    <div class="dropdown">
        <a href="@Url.Action("Index", "Home")" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
            <i class="fa fa-mail-reply w3-xxlarge"></i>
            <p>IPG HOME</p>
        </a>
    </div>
</nav>

IPGMMS/IPGMMS/Views/Shared/_GoogleMap.cshtml
@model IPGMMS.ViewModels.MemberDetails

<!--This is the partial view that renders a Google map based on the mapURL string that is in the ContactInfo.Meta
    partial class. Will render a view of the world if there is no information for the address of the groomer.-->

<div class="row col-md-12">
    <iframe width="450" height="300"  frameborder="0" style="border:0" src="@Url.Content(Model.Contact.mapURL)" )></iframe>
</div>

IPGMMS/IPGMMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IPGMMS</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/ipgLogoFavicon.ico" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/w3.css")
    @Styles.Render("~/Content/SharedLayout.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body class="w3-content" style="max-width:100%">

    <!-- Sidebar (hidden by default) -->
    <nav class="w3-sidebar w3-bar-block w3-card-2 w3-top w3-xlarge w3-animate-left w3-light-gray" style="display:none;z-index:2;width:40%;max-width:300px" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button"><i class="fa fa-close"></i></a>
        <div class="w3-padding-12"><a href="@Url.Action("Index", "Home")"><img src="~/Content/Images/IPGLogo2.png" /></a></div>
        <a href="@Url.Action("Index","Map")" onclick="w3_close()" class="w3-bar-item w3-button">IPG Member Search</a>
        <a href="@Url.Action("Index","Member")" onclick="w3_close()" class="w3-bar-item w3-button">View All Members</a>

    </nav>

    <!-- Top menu -->
    <div class="w3-top w3-light-gray w3-padding-right">
        <div class="w3-xlarge" style="max-width:100%; margin:auto">
            <div class="w3-button w3-left navButton" onclick="w3_open()"><i class="fa fa-bars w3-xxlarge navButton"></i></div>
            <div class="w3-right">@Html.Partial("_LoginPartial")</div>
            <div class="w3-left"><h4 class="w3-hide-small"><a href="@Url.Action("Index", "Home")">International Professional Groomers, Inc.</a></h4></div>
        </div>
    </div>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- Page Content -->
    <div class="w3-padding-large" id="main">
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>

    <!-- Footer -->
    <footer class="w3-container w3-padding-32 w3-dark-grey">
        <div class="w3-row-padding">
            <div class="w3-half w3-padding-left">
                <h3><a href="@Url.Action("Index","Home")">Home</a></h3>
                <h3><a href="@Url.Action("About","Home")">About IPG</a></h3>
                <h3><a href="@Url.Action("FAQ", "Home")">FAQ</a></h3>
                <h3><a href="@Url.Action("Contact", "Home")">Contact IPG</a></h3> 
                <h3><a href="@Url.Action("StarTechCredits","Home")">StarTech Credits</a></h3>              
            </div>
            <div class="w3-half w3-padding-right w3-padding-left">
                <a href="@Url.Action("Underconstruction","Home")"><h3>IPG Certification Tracks</h3></a>
                <a href="@Url.Action("Underconstruction","Home")"><h3>IPG Events</h3></a>
                <a href="@Url.Action("Underconstruction","Home")"><h3>IPG Products</h3></a>
                <i class="fa fa-facebook"></i>
                <i class="fa fa-instagram"></i>
                <i class="fa fa-twitter"></i>
                <i class="fa fa-youtube"></i>    
            </div>
        </div>
    </footer>



    <!-- END PAGE CONTENT -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/SharedLayout.js")
    @RenderSection("scripts", required: false)

</body>

</html>

IPGMMS/IPGMMS/Views/Shared/_LayoutOLD.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IPGMMS</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/w3.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            @*<div class="row col-md-3">
                    <img src="~/Content/Images/IPGLogo2.jpeg" alt="Top Logo" />
                </div>
                <h1 class="row col-md-9">International Professional Groomers, Inc<br /><small>Member Management System</small></h1>*@
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IPGMMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("IPG Members", "Index", "Member")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("FAQ", "FAQ", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <hr />
        <p>&copy; @DateTime.Now.Year - StarTech Application</p>
        <img src="~/Content/Images/IPGLogo.jpg" alt="Bottom Logo" />
    </footer>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

IPGMMS/IPGMMS/Views/Shared/_LeftNav.cshtml
@{
    ViewBag.Title = "Home Page";
}


<br>
<br>

<link href="@Url.Content("~/Content/Homepage.css")" rel="stylesheet" type="text/css" />

<div class="left-navbar">
    <div class="topLogo">
        <img src="~/Content/Images/IPGLogo2.jpeg" alt="Top Logo" />
    </div>
    <p>
        Links go here, these not in order. Will need to touch up once links are established.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About IPG", "About", "Home")</li>
        <li>@Html.ActionLink("Contact IPG", "Contact", "Home")</li>
        <li>@Html.ActionLink("FAQ", "FAQ", "Home")</li>
        <li>@Html.ActionLink("Members", "Index", "Member")</li>
        <li>@Html.ActionLink("Admin", "Index", "Portal")</li>
        <li>Yupe, you guessed it.</li>
        <li>Another one</li>
        <li>And another</li>
        <li>And another</li>
        <li>Hi</li>
    </ul>
</div>